package repository

import (
	"context"
	"fmt"
	"strings"

	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/domain"
)

// GENERATED BY CODEX START: query data snapshot Pemda untuk endpoint GET.
func (repo *PenetapanPemdaRepository) FindTujuanPemdaBySnapshot(
	ctx context.Context,
	snapshotID int64,
	tahun int,
) ([]domain.TujuanPemdaPenetapan, error) {
	const query = `
		SELECT id, kode_tujuan_pemda, visi, misi, tujuan_pemda, periode, tahun_aktif,
			created_date, last_modified_date, created_by, penetapan_pemda_id
		FROM tujuan_pemda_penetapan
		WHERE penetapan_pemda_id = $1 AND tahun_aktif = $2
		ORDER BY id ASC`

	rows, err := repo.DB.QueryContext(ctx, query, snapshotID, tahun)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	result := make([]domain.TujuanPemdaPenetapan, 0)
	for rows.Next() {
		var item domain.TujuanPemdaPenetapan
		if err := rows.Scan(
			&item.Id,
			&item.KodeTujuanPemda,
			&item.Visi,
			&item.Misi,
			&item.TujuanPemda,
			&item.Periode,
			&item.TahunAktif,
			&item.CreatedDate,
			&item.LastModifiedDate,
			&item.CreatedBy,
			&item.PenetapanPemdaId,
		); err != nil {
			return nil, err
		}
		result = append(result, item)
	}

	return result, rows.Err()
}

func (repo *PenetapanPemdaRepository) FindIndikatorTujuanPemdaByTujuanIDs(
	ctx context.Context,
	tujuanIDs []int64,
) ([]domain.IndikatorTujuanPemdaPenetapan, error) {
	if len(tujuanIDs) == 0 {
		return []domain.IndikatorTujuanPemdaPenetapan{}, nil
	}

	query, args := buildIDsQuery(`
		SELECT id, tujuan_pemda_id, kode_indikator, indikator, rumus_perhitungan,
			sumber_data, definisi_operasional, tahun_aktif, created_date,
			last_modified_date, created_by
		FROM indikator_tujuan_pemda_penetapan
		WHERE tujuan_pemda_id IN (%s)
		ORDER BY id ASC`, tujuanIDs)
	rows, err := repo.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	result := make([]domain.IndikatorTujuanPemdaPenetapan, 0, len(tujuanIDs))
	for rows.Next() {
		var item domain.IndikatorTujuanPemdaPenetapan
		if err := rows.Scan(
			&item.Id,
			&item.IdTujuanPemda,
			&item.KodeIndikator,
			&item.Indikator,
			&item.RumusPerhitungan,
			&item.SumberData,
			&item.DefinisiOperasional,
			&item.TahunAktif,
			&item.CreatedDate,
			&item.LastModifiedDate,
			&item.CreatedBy,
		); err != nil {
			return nil, err
		}
		result = append(result, item)
	}

	return result, rows.Err()
}

func (repo *PenetapanPemdaRepository) FindTargetIndikatorTujuanPemdaByIndikatorIDs(
	ctx context.Context,
	indikatorIDs []int64,
) ([]domain.TargetIndikatorTujuanPemdaPenetapan, error) {
	if len(indikatorIDs) == 0 {
		return []domain.TargetIndikatorTujuanPemdaPenetapan{}, nil
	}

	query, args := buildIDsQuery(`
		SELECT id, indikator_tujuan_pemda_id, kode_target, tahun, target, satuan,
			created_date, last_modified_date, created_by
		FROM target_indikator_tujuan_pemda_penetapan
		WHERE indikator_tujuan_pemda_id IN (%s)
		ORDER BY id ASC`, indikatorIDs)
	rows, err := repo.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	result := make([]domain.TargetIndikatorTujuanPemdaPenetapan, 0, len(indikatorIDs))
	for rows.Next() {
		var item domain.TargetIndikatorTujuanPemdaPenetapan
		if err := rows.Scan(
			&item.Id,
			&item.IndikatorTujuanPemdaId,
			&item.KodeTarget,
			&item.Tahun,
			&item.Target,
			&item.Satuan,
			&item.CreatedDate,
			&item.LastModifiedDate,
			&item.CreatedBy,
		); err != nil {
			return nil, err
		}
		result = append(result, item)
	}

	return result, rows.Err()
}

func (repo *PenetapanPemdaRepository) FindSasaranPemdaBySnapshot(
	ctx context.Context,
	snapshotID int64,
	tahun int,
) ([]domain.SasaranPemdaPenetapan, error) {
	const query = `
		SELECT id, kode_tujuan_pemda, kode_sasaran_pemda, sasaran_pemda, periode, tahun_aktif,
			created_date, last_modified_date, created_by, penetapan_pemda_id
		FROM sasaran_pemda_penetapan
		WHERE penetapan_pemda_id = $1 AND tahun_aktif = $2
		ORDER BY id ASC`

	rows, err := repo.DB.QueryContext(ctx, query, snapshotID, tahun)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	result := make([]domain.SasaranPemdaPenetapan, 0)
	for rows.Next() {
		var item domain.SasaranPemdaPenetapan
		if err := rows.Scan(
			&item.Id,
			&item.KodeTujuanPemda,
			&item.KodeSasaranPemda,
			&item.SasaranPemda,
			&item.Periode,
			&item.TahunAktif,
			&item.CreatedDate,
			&item.LastModifiedDate,
			&item.CreatedBy,
			&item.PenetapanPemdaId,
		); err != nil {
			return nil, err
		}
		result = append(result, item)
	}

	return result, rows.Err()
}

func (repo *PenetapanPemdaRepository) FindIndikatorSasaranPemdaBySasaranIDs(
	ctx context.Context,
	sasaranIDs []int64,
) ([]domain.IndikatorSasaranPemdaPenetapan, error) {
	if len(sasaranIDs) == 0 {
		return []domain.IndikatorSasaranPemdaPenetapan{}, nil
	}

	query, args := buildIDsQuery(`
		SELECT id, sasaran_pemda_id, kode_indikator, indikator, rumus_perhitungan,
			sumber_data, definisi_operasional, tahun_aktif, created_date,
			last_modified_date, created_by
		FROM indikator_sasaran_pemda_penetapan
		WHERE sasaran_pemda_id IN (%s)
		ORDER BY id ASC`, sasaranIDs)
	rows, err := repo.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	result := make([]domain.IndikatorSasaranPemdaPenetapan, 0, len(sasaranIDs))
	for rows.Next() {
		var item domain.IndikatorSasaranPemdaPenetapan
		if err := rows.Scan(
			&item.Id,
			&item.IdSasaranPemda,
			&item.KodeIndikator,
			&item.Indikator,
			&item.RumusPerhitungan,
			&item.SumberData,
			&item.DefinisiOperasional,
			&item.TahunAktif,
			&item.CreatedDate,
			&item.LastModifiedDate,
			&item.CreatedBy,
		); err != nil {
			return nil, err
		}
		result = append(result, item)
	}

	return result, rows.Err()
}

func (repo *PenetapanPemdaRepository) FindTargetIndikatorSasaranPemdaByIndikatorIDs(
	ctx context.Context,
	indikatorIDs []int64,
) ([]domain.TargetIndikatorSasaranPemdaPenetapan, error) {
	if len(indikatorIDs) == 0 {
		return []domain.TargetIndikatorSasaranPemdaPenetapan{}, nil
	}

	query, args := buildIDsQuery(`
		SELECT id, indikator_sasaran_pemda_id, kode_target, tahun, target, satuan,
			created_date, last_modified_date, created_by
		FROM target_indikator_sasaran_pemda_penetapan
		WHERE indikator_sasaran_pemda_id IN (%s)
		ORDER BY id ASC`, indikatorIDs)
	rows, err := repo.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	result := make([]domain.TargetIndikatorSasaranPemdaPenetapan, 0, len(indikatorIDs))
	for rows.Next() {
		var item domain.TargetIndikatorSasaranPemdaPenetapan
		if err := rows.Scan(
			&item.Id,
			&item.IndikatorSasaranId,
			&item.KodeTarget,
			&item.Tahun,
			&item.Target,
			&item.Satuan,
			&item.CreatedDate,
			&item.LastModifiedDate,
			&item.CreatedBy,
		); err != nil {
			return nil, err
		}
		result = append(result, item)
	}

	return result, rows.Err()
}

func buildIDsQuery(query string, ids []int64) (string, []any) {
	placeholders := make([]string, len(ids))
	args := make([]any, len(ids))
	for i, id := range ids {
		placeholders[i] = fmt.Sprintf("$%d", i+1)
		args[i] = id
	}

	return fmt.Sprintf(query, strings.Join(placeholders, ",")), args
}

// GENERATED BY CODEX END
