package repository

import (
	"context"
	"database/sql"

	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/domain"
)

// GENERATED BY CODEX START: persistence sasaran Pemda dan turunannya.
func (repo *PenetapanPemdaRepository) SaveSasaranPemdaPenetapan(
	ctx context.Context,
	tx *sql.Tx,
	sasaran domain.SasaranPemdaPenetapan,
) (int64, error) {
	const query = `
		INSERT INTO sasaran_pemda_penetapan
			(penetapan_pemda_id, kode_sasaran_pemda, sasaran_pemda, periode, tahun_aktif, created_by)
		VALUES ($1, $2, $3, $4, $5, $6)
		RETURNING id`

	var id int64
	if err := tx.QueryRowContext(
		ctx, query,
		sasaran.PenetapanPemdaId,
		sasaran.KodeSasaranPemda,
		sasaran.SasaranPemda,
		sasaran.Periode,
		sasaran.TahunAktif,
		sasaran.CreatedBy,
	).Scan(&id); err != nil {
		return 0, err
	}

	return id, nil
}

func (repo *PenetapanPemdaRepository) SaveIndikatorSasaranPemdaPenetapan(
	ctx context.Context,
	tx *sql.Tx,
	indikator domain.IndikatorSasaranPemdaPenetapan,
) (int64, error) {
	const query = `
		INSERT INTO indikator_sasaran_pemda_penetapan
			(sasaran_pemda_id, kode_indikator, indikator, rumus_perhitungan, sumber_data,
			 definisi_operasional, tahun_aktif, created_by)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		RETURNING id`

	var id int64
	if err := tx.QueryRowContext(
		ctx, query,
		indikator.IdSasaranPemda,
		indikator.KodeIndikator,
		indikator.Indikator,
		indikator.RumusPerhitungan,
		indikator.SumberData,
		indikator.DefinisiOperasional,
		indikator.TahunAktif,
		indikator.CreatedBy,
	).Scan(&id); err != nil {
		return 0, err
	}

	return id, nil
}

func (repo *PenetapanPemdaRepository) SaveTargetIndikatorSasaranPemdaPenetapan(
	ctx context.Context,
	tx *sql.Tx,
	target domain.TargetIndikatorSasaranPemdaPenetapan,
) (int64, error) {
	const query = `
		INSERT INTO target_indikator_sasaran_pemda_penetapan
			(indikator_sasaran_pemda_id, kode_target, tahun, target, satuan, created_by)
		VALUES ($1, $2, $3, $4, $5, $6)
		RETURNING id`

	var id int64
	if err := tx.QueryRowContext(
		ctx, query,
		target.IndikatorSasaranId,
		target.KodeTarget,
		target.Tahun,
		target.Target,
		target.Satuan,
		target.CreatedBy,
	).Scan(&id); err != nil {
		return 0, err
	}

	return id, nil
}

// GENERATED BY CODEX END
