package repository

import (
	"context"
	"database/sql"

	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/domain"
)

// GENERATED BY CODEX START: persistence snapshot penetapan Pemda.
func (repo *PenetapanPemdaRepository) GetPenetapanNextVersion(
	ctx context.Context,
	tx *sql.Tx,
	snapshot domain.SnapshotPenetapan,
) (int, error) {
	const query = `
		SELECT COALESCE(MAX(versi), 0) + 1
		FROM penetapan_pemda
		WHERE tahun = $1 AND jenis_penetapan = $2`

	var versi int
	if err := tx.QueryRowContext(ctx, query, snapshot.Tahun, snapshot.JenisSnapshot).Scan(&versi); err != nil {
		return 0, err
	}

	return versi, nil
}

func (repo *PenetapanPemdaRepository) DeactivateOldSnapshot(
	ctx context.Context,
	tx *sql.Tx,
	snapshot domain.SnapshotPenetapan,
) error {
	const query = `
		UPDATE penetapan_pemda
		SET snapshot_status = $3, is_active = FALSE
		WHERE tahun = $1 AND jenis_penetapan = $2 AND is_active = TRUE`

	_, err := tx.ExecContext(
		ctx,
		query,
		snapshot.Tahun,
		snapshot.JenisSnapshot,
		domain.SnapshotStatusArchived,
	)
	return err
}

func (repo *PenetapanPemdaRepository) SaveSnapshot(
	ctx context.Context,
	tx *sql.Tx,
	snapshot domain.SnapshotPenetapan,
) (int64, error) {
	const query = `
		INSERT INTO penetapan_pemda
			(tahun, jenis_penetapan, versi, snapshot_status, generated_by, is_active)
		VALUES ($1, $2, $3, $4, $5, $6)
		RETURNING id`

	var id int64
	if err := tx.QueryRowContext(
		ctx,
		query,
		snapshot.Tahun,
		snapshot.JenisSnapshot,
		snapshot.Versi,
		snapshot.SnapshotStatus,
		snapshot.GeneratedBy,
		snapshot.IsActive,
	).Scan(&id); err != nil {
		return 0, err
	}

	return id, nil
}

// GENERATED BY CODEX END
