package repository

import (
	"context"
	"database/sql"

	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/domain"
)

// GENERATED BY CODEX START: persistence tujuan Pemda dan turunannya.
func (repo *PenetapanPemdaRepository) SaveTujuanPemdaPenetapan(
	ctx context.Context,
	tx *sql.Tx,
	tujuan domain.TujuanPemdaPenetapan,
) (int64, error) {
	const query = `
		INSERT INTO tujuan_pemda_penetapan
			(penetapan_pemda_id, kode_tujuan_pemda, visi, misi, tujuan_pemda, periode, tahun_aktif, created_by)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		RETURNING id`

	var id int64
	if err := tx.QueryRowContext(
		ctx,
		query,
		tujuan.PenetapanPemdaId,
		tujuan.KodeTujuanPemda,
		tujuan.Visi,
		tujuan.Misi,
		tujuan.TujuanPemda,
		tujuan.Periode,
		tujuan.TahunAktif,
		tujuan.CreatedBy,
	).Scan(&id); err != nil {
		return 0, err
	}

	return id, nil
}

func (repo *PenetapanPemdaRepository) SaveIndikatorTujuanPemdaPenetapan(
	ctx context.Context,
	tx *sql.Tx,
	indikator domain.IndikatorTujuanPemdaPenetapan,
) (int64, error) {
	const query = `
		INSERT INTO indikator_tujuan_pemda_penetapan
			(tujuan_pemda_id, kode_indikator, indikator, rumus_perhitungan, sumber_data,
			 definisi_operasional, tahun_aktif, created_by)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		RETURNING id`

	var id int64
	if err := tx.QueryRowContext(
		ctx,
		query,
		indikator.IdTujuanPemda,
		indikator.KodeIndikator,
		indikator.Indikator,
		indikator.RumusPerhitungan,
		indikator.SumberData,
		indikator.DefinisiOperasional,
		indikator.TahunAktif,
		indikator.CreatedBy,
	).Scan(&id); err != nil {
		return 0, err
	}

	return id, nil
}

func (repo *PenetapanPemdaRepository) SaveTargetIndikatorTujuanPemdaPenetapan(
	ctx context.Context,
	tx *sql.Tx,
	target domain.TargetIndikatorTujuanPemdaPenetapan,
) (int64, error) {
	const query = `
		INSERT INTO target_indikator_tujuan_pemda_penetapan
			(indikator_tujuan_pemda_id, kode_target, tahun, target, satuan, created_by)
		VALUES ($1, $2, $3, $4, $5, $6)
		RETURNING id`

	var id int64
	if err := tx.QueryRowContext(
		ctx,
		query,
		target.IndikatorTujuanPemdaId,
		target.KodeTarget,
		target.Tahun,
		target.Target,
		target.Satuan,
		target.CreatedBy,
	).Scan(&id); err != nil {
		return 0, err
	}

	return id, nil
}

// GENERATED BY CODEX END
