package web

// GENERATED BY CODEX START: response endpoint GET tujuan dan sasaran Pemda.
type TujuanPenetapanPemdaResponse struct {
	TahunAktif int                   `json:"tahun_aktif" example:"2025"`
	Versi      int                   `json:"versi" example:"1"`
	IsLocked   bool                  `json:"is_locked" example:"true"`
	Tujuans    []TujuanPemdaResponse `json:"tujuan_pemdas"`
}

type TujuanPemdaResponse struct {
	Id              int64                             `json:"id" example:"1"`
	Visi            string                            `json:"visi" example:"Terpenuhinya ..."`
	Misi            string                            `json:"misi" example:"Misi Kota 1"`
	KodeTujuanPemda string                            `json:"kode_tujuan_pemda" example:"TUJ-PEM-1"`
	TujuanPemda     string                            `json:"tujuan_pemda" example:"Tujuan Pemda 1"`
	Periode         string                            `json:"periode" example:"2025-2030"`
	Indikator       []IndikatorPemdaPenetapanResponse `json:"indikators"`
}

type SasaranPenetapanPemdaResponse struct {
	TahunAktif int                    `json:"tahun_aktif" example:"2025"`
	Versi      int                    `json:"versi" example:"1"`
	IsLocked   bool                   `json:"is_locked" example:"true"`
	Sasarans   []SasaranPemdaResponse `json:"sasaran_pemdas"`
}

type SasaranPemdaResponse struct {
	Id               int64                             `json:"id" example:"1"`
	KodeSasaranPemda string                            `json:"kode_sasaran_pemda" example:"SAS-PEM-1"`
	SasaranPemda     string                            `json:"sasaran_pemda" example:"SASARAN PENUNJANG"`
	Periode          string                            `json:"periode" example:"2025-2030"`
	Indikator        []IndikatorPemdaPenetapanResponse `json:"indikators"`
}

type IndikatorPemdaPenetapanResponse struct {
	Id                  int64                 `json:"id"`
	KodeIndikator       string                `json:"kode_indikator"`
	Indikator           string                `json:"indikator"`
	RumusPerhitungan    *string               `json:"rumus_perhitungan"`
	SumberData          *string               `json:"sumber_data"`
	DefinisiOperasional *string               `json:"definisi_operasional"`
	TahunAktif          int                   `json:"tahun_aktif"`
	Target              []TargetPemdaResponse `json:"targets"`
}

type TargetPemdaResponse struct {
	Id         int64   `json:"id"`
	KodeTarget string  `json:"kode_target"`
	Tahun      int     `json:"tahun"`
	Target     float64 `json:"target"`
	Satuan     string  `json:"satuan"`
}

// GENERATED BY CODEX END
