package service

import (
	"context"
	"log/slog"
	"time"

	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/client"
	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/domain"
	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/repository"
	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/service/sync"
	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/web"
)

type PenetapanPemdaService struct {
	Repo         *repository.PenetapanPemdaRepository
	Client       *client.Client
	SyncExecutor *sync.Registry
	Logger       *slog.Logger
}

func NewPenetapanPemdaService(
	repo *repository.PenetapanPemdaRepository,
	client *client.Client,
	syncExecutor *sync.Registry,
	logger *slog.Logger,
) *PenetapanPemdaService {
	return &PenetapanPemdaService{
		Repo:         repo,
		Client:       client,
		SyncExecutor: syncExecutor,
		Logger:       logger,
	}
}

// GENERATED BY CODEX START: pembacaan snapshot tujuan dan sasaran Pemda dari database internal.
func (s *PenetapanPemdaService) FindTujuanPemda(
	ctx context.Context,
	tahun int,
) (web.TujuanPenetapanPemdaResponse, error) {
	snapshot, err := s.getActiveSnapshot(ctx, tahun, domain.JenisPenetapanTujuanPemda)
	if err != nil {
		return web.TujuanPenetapanPemdaResponse{}, err
	}

	tujuans, err := s.Repo.FindTujuanPemdaBySnapshot(ctx, snapshot.Id, tahun)
	if err != nil {
		return web.TujuanPenetapanPemdaResponse{}, err
	}
	tujuanIDs := make([]int64, 0, len(tujuans))
	for _, tujuan := range tujuans {
		tujuanIDs = append(tujuanIDs, tujuan.Id)
	}

	indikators, err := s.Repo.FindIndikatorTujuanPemdaByTujuanIDs(ctx, tujuanIDs)
	if err != nil {
		return web.TujuanPenetapanPemdaResponse{}, err
	}
	indikatorIDs := make([]int64, 0, len(indikators))
	for _, indikator := range indikators {
		indikatorIDs = append(indikatorIDs, indikator.Id)
	}

	targets, err := s.Repo.FindTargetIndikatorTujuanPemdaByIndikatorIDs(ctx, indikatorIDs)
	if err != nil {
		return web.TujuanPenetapanPemdaResponse{}, err
	}

	targetMap := make(map[int64][]web.TargetPemdaResponse)
	for _, target := range targets {
		targetMap[target.IndikatorTujuanPemdaId] = append(
			targetMap[target.IndikatorTujuanPemdaId],
			web.TargetPemdaResponse{
				Id:         target.Id,
				KodeTarget: target.KodeTarget,
				Tahun:      target.Tahun,
				Target:     target.Target,
				Satuan:     target.Satuan,
			},
		)
	}

	indikatorMap := make(map[int64][]web.IndikatorPemdaPenetapanResponse)
	for _, indikator := range indikators {
		indikatorMap[indikator.IdTujuanPemda] = append(
			indikatorMap[indikator.IdTujuanPemda],
			web.IndikatorPemdaPenetapanResponse{
				Id:                  indikator.Id,
				KodeIndikator:       indikator.KodeIndikator,
				Indikator:           indikator.Indikator,
				RumusPerhitungan:    indikator.RumusPerhitungan,
				SumberData:          indikator.SumberData,
				DefinisiOperasional: indikator.DefinisiOperasional,
				TahunAktif:          indikator.TahunAktif,
				Target:              targetMap[indikator.Id],
			},
		)
	}

	response := make([]web.TujuanPemdaResponse, 0, len(tujuans))
	for _, tujuan := range tujuans {
		response = append(response, web.TujuanPemdaResponse{
			Id:              tujuan.Id,
			KodeTujuanPemda: tujuan.KodeTujuanPemda,
			Visi:            tujuan.Visi,
			Misi:            tujuan.Misi,
			TujuanPemda:     tujuan.TujuanPemda,
			Periode:         tujuan.Periode,
			Indikator:       indikatorMap[tujuan.Id],
		})
	}

	return web.TujuanPenetapanPemdaResponse{
		TahunAktif: tahun,
		Versi:      snapshot.Versi,
		IsLocked:   true,
		Tujuans:    response,
	}, nil
}

func (s *PenetapanPemdaService) FindSasaranPemda(
	ctx context.Context,
	tahun int,
) (web.SasaranPenetapanPemdaResponse, error) {
	snapshot, err := s.getActiveSnapshot(ctx, tahun, domain.JenisPenetapanSasaranPemda)
	if err != nil {
		return web.SasaranPenetapanPemdaResponse{}, err
	}

	sasarans, err := s.Repo.FindSasaranPemdaBySnapshot(ctx, snapshot.Id, tahun)
	if err != nil {
		return web.SasaranPenetapanPemdaResponse{}, err
	}
	sasaranIDs := make([]int64, 0, len(sasarans))
	for _, sasaran := range sasarans {
		sasaranIDs = append(sasaranIDs, sasaran.Id)
	}

	indikators, err := s.Repo.FindIndikatorSasaranPemdaBySasaranIDs(ctx, sasaranIDs)
	if err != nil {
		return web.SasaranPenetapanPemdaResponse{}, err
	}
	indikatorIDs := make([]int64, 0, len(indikators))
	for _, indikator := range indikators {
		indikatorIDs = append(indikatorIDs, indikator.Id)
	}

	targets, err := s.Repo.FindTargetIndikatorSasaranPemdaByIndikatorIDs(ctx, indikatorIDs)
	if err != nil {
		return web.SasaranPenetapanPemdaResponse{}, err
	}

	targetMap := make(map[int64][]web.TargetPemdaResponse)
	for _, target := range targets {
		targetMap[target.IndikatorSasaranId] = append(
			targetMap[target.IndikatorSasaranId],
			web.TargetPemdaResponse{
				Id:         target.Id,
				KodeTarget: target.KodeTarget,
				Tahun:      target.Tahun,
				Target:     target.Target,
				Satuan:     target.Satuan,
			},
		)
	}

	indikatorMap := make(map[int64][]web.IndikatorPemdaPenetapanResponse)
	for _, indikator := range indikators {
		indikatorMap[indikator.IdSasaranPemda] = append(
			indikatorMap[indikator.IdSasaranPemda],
			web.IndikatorPemdaPenetapanResponse{
				Id:                  indikator.Id,
				KodeIndikator:       indikator.KodeIndikator,
				Indikator:           indikator.Indikator,
				RumusPerhitungan:    indikator.RumusPerhitungan,
				SumberData:          indikator.SumberData,
				DefinisiOperasional: indikator.DefinisiOperasional,
				TahunAktif:          indikator.TahunAktif,
				Target:              targetMap[indikator.Id],
			},
		)
	}

	response := make([]web.SasaranPemdaResponse, 0, len(sasarans))
	for _, sasaran := range sasarans {
		response = append(response, web.SasaranPemdaResponse{
			Id:               sasaran.Id,
			KodeTujuanPemda:  sasaran.KodeTujuanPemda,
			KodeSasaranPemda: sasaran.KodeSasaranPemda,
			SasaranPemda:     sasaran.SasaranPemda,
			Periode:          sasaran.Periode,
			Indikator:        indikatorMap[sasaran.Id],
		})
	}

	return web.SasaranPenetapanPemdaResponse{
		TahunAktif: tahun,
		Versi:      snapshot.Versi,
		IsLocked:   true,
		Sasarans:   response,
	}, nil
}

func (s *PenetapanPemdaService) getActiveSnapshot(
	ctx context.Context,
	tahun int,
	jenisPenetapan domain.JenisPenetapan,
) (*domain.ActiveSnapshot, error) {
	snapshot, err := s.Repo.GetActiveSnapshot(ctx, tahun, jenisPenetapan)
	if err != nil {
		s.Logger.Error("ambil snapshot aktif Pemda gagal", "err", err)
		return nil, err
	}
	if snapshot == nil {
		s.Logger.WarnContext(
			ctx,
			"snapshot aktif Pemda tidak ditemukan",
			"tahun", tahun,
			"jenis_penetapan", jenisPenetapan,
		)
		return &domain.ActiveSnapshot{}, nil
	}

	return snapshot, nil
}

// GENERATED BY CODEX END

func (s *PenetapanPemdaService) SyncPenetapanTujuanPemda(
	ctx context.Context,
	req *web.SyncPenetapanRequest,
) (web.SyncPenetapanResponse, error) {
	now := time.Now()
	currentUser := "super_admin" // ambil dari ctx nanti
	jenisPenetapan := domain.JenisPenetapanTujuanPemda

	executor, err := s.SyncExecutor.Get(jenisPenetapan)
	if err != nil {
		s.Logger.Error("ERROR GET EXECUTOR", "err", err)
		return web.SyncPenetapanResponse{}, err
	}

	// insert metadata pertama
	metadata := domain.SyncPenetapanMetadata{
		Tahun:          req.Tahun,
		Status:         domain.SyncStatusPending,
		StartedAt:      now,
		SyncBy:         &currentUser,
		JenisPenetapan: jenisPenetapan,
	}

	// log start
	s.Logger.InfoContext(
		ctx,
		"sync penetapan pk individu started",
		"tahun", metadata.Tahun,
		"jenis_sync", metadata.JenisPenetapan,
		"sync_by", metadata.SyncBy,
		"started_at", metadata.StartedAt,
	)

	syncId, err := s.Repo.InsertMetadata(ctx, metadata)
	if err != nil {
		s.Logger.Error("ERROR INSERT METADATA", "err", err)
		return web.SyncPenetapanResponse{}, err
	}

	// updateMetadata jadi InProgress
	err = s.markSyncAsInProgress(ctx, syncId)
	if err != nil {
		s.Logger.Error("ERROR INSERT METADATA SYNC IN PROGRESS", "err", err)
		return web.SyncPenetapanResponse{}, err
	}

	// SYNC AND SAVE
	summary, err := executor.Sync(ctx, syncId, req, currentUser)
	if err != nil {
		s.Logger.Error("ERROR SYNC DATA", "err", err)
		return web.SyncPenetapanResponse{}, s.failSync(ctx, syncId, err)
	}

	// jika berhasil updateMetadata jadi Success
	err = s.markSyncAsSuccess(ctx, syncId)
	if err != nil {
		s.Logger.Error("ERROR INSERT METADATA SYNC SUCCESS", "err", err)
		return web.SyncPenetapanResponse{}, err
	}

	return web.SyncPenetapanResponse{
		SyncId:           syncId,
		Status:           domain.SyncStatusSuccess,
		Tahun:            req.Tahun,
		JenisPenetapan:   jenisPenetapan,
		ProcessedAt:      time.Now(),
		ProcessedSummary: summary,
	}, nil
}

// GENERATED BY CODEX START: service sinkronisasi sasaran Pemda.
func (s *PenetapanPemdaService) SyncPenetapanSasaranPemda(
	ctx context.Context,
	req *web.SyncPenetapanRequest,
) (web.SyncPenetapanResponse, error) {
	now := time.Now()
	currentUser := "super_admin" // ambil dari ctx nanti
	jenisPenetapan := domain.JenisPenetapanSasaranPemda

	executor, err := s.SyncExecutor.Get(jenisPenetapan)
	if err != nil {
		s.Logger.Error("executor sync sasaran Pemda tidak ditemukan", "err", err)
		return web.SyncPenetapanResponse{}, err
	}

	metadata := domain.SyncPenetapanMetadata{
		Tahun:          req.Tahun,
		Status:         domain.SyncStatusPending,
		StartedAt:      now,
		SyncBy:         &currentUser,
		JenisPenetapan: jenisPenetapan,
	}

	syncID, err := s.Repo.InsertMetadata(ctx, metadata)
	if err != nil {
		s.Logger.Error("simpan metadata sync sasaran Pemda gagal", "err", err)
		return web.SyncPenetapanResponse{}, err
	}

	if err := s.markSyncAsInProgress(ctx, syncID); err != nil {
		s.Logger.Error("ubah metadata sync sasaran Pemda ke in progress gagal", "err", err)
		return web.SyncPenetapanResponse{}, err
	}

	summary, err := executor.Sync(ctx, syncID, req, currentUser)
	if err != nil {
		s.Logger.Error("sync sasaran Pemda gagal", "err", err)
		return web.SyncPenetapanResponse{}, s.failSync(ctx, syncID, err)
	}

	if err := s.markSyncAsSuccess(ctx, syncID); err != nil {
		s.Logger.Error("ubah metadata sync sasaran Pemda ke success gagal", "err", err)
		return web.SyncPenetapanResponse{}, err
	}

	return web.SyncPenetapanResponse{
		SyncId:           syncID,
		Status:           domain.SyncStatusSuccess,
		Tahun:            req.Tahun,
		JenisPenetapan:   jenisPenetapan,
		ProcessedAt:      time.Now(),
		ProcessedSummary: summary,
	}, nil
}

// GENERATED BY CODEX END

func (s *PenetapanPemdaService) markSyncAsFailed(ctx context.Context, syncId int64, msg string) error {
	statusSync := domain.SyncStatusFailed
	errorMessage := &msg
	return s.Repo.UpdateMetadataStatus(
		ctx,
		syncId,
		statusSync,
		errorMessage,
	)
}

func (s *PenetapanPemdaService) markSyncAsInProgress(ctx context.Context, syncId int64) error {
	statusSync := domain.SyncStatusInProgress
	return s.Repo.UpdateMetadataStatus(
		ctx,
		syncId,
		statusSync,
		nil,
	)
}

func (s *PenetapanPemdaService) markSyncAsSuccess(ctx context.Context, syncId int64) error {
	statusSync := domain.SyncStatusSuccess
	return s.Repo.UpdateMetadataStatus(
		ctx,
		syncId,
		statusSync,
		nil,
	)
}

func (s *PenetapanPemdaService) failSync(ctx context.Context, syncId int64, cause error) error {
	updateErr := s.markSyncAsFailed(
		ctx,
		syncId,
		cause.Error(),
	)
	if updateErr != nil {
		return updateErr
	}
	return cause
}

func (s *PenetapanPemdaService) FindTujuanSasaranPemda(
	ctx context.Context,
	tahun int,
) (web.TujuanSasaranPenetapanPemdaResponse, error) {
	tujuans, err := s.FindTujuanPemda(ctx, tahun)
	if err != nil {
		s.Logger.Error("FindTujuanPemda")
		return web.TujuanSasaranPenetapanPemdaResponse{}, err
	}

	sasarans, err := s.FindSasaranPemda(ctx, tahun)
	if err != nil {
		s.Logger.Error("FindSasaranPemda")
		return web.TujuanSasaranPenetapanPemdaResponse{}, err
	}

	sasaranMap := make(map[string][]web.SasaranPemdaResponse)

	for _, sasaran := range sasarans.Sasarans {
		sasaranMap[sasaran.KodeTujuanPemda] = append(
			sasaranMap[sasaran.KodeTujuanPemda],
			sasaran,
		)
	}

	response := make(
		[]web.TujuanWithSasaranPemdaResponse,
		0,
		len(tujuans.Tujuans),
	)
	for _, tujuan := range tujuans.Tujuans {
		response = append(response, web.TujuanWithSasaranPemdaResponse{
			Id:              tujuan.Id,
			KodeTujuanPemda: tujuan.KodeTujuanPemda,
			Visi:            tujuan.Visi,
			Misi:            tujuan.Misi,
			TujuanPemda:     tujuan.TujuanPemda,
			Periode:         tujuan.Periode,
			Indikator:       tujuan.Indikator,
			SasaranPemda:    sasaranMap[tujuan.KodeTujuanPemda],
		})
	}

	return web.TujuanSasaranPenetapanPemdaResponse{
		TahunAktif: tahun,
		Versi:      tujuans.Versi,
		IsLocked:   true,
		Tujuans:    response,
	}, nil
}
