package api

import (
	"net/http"
	"strconv"

	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/web"
	"github.com/bappeda-dev-team/penetapan-service/internal/validator"
)

// SyncPenetapanTujuanPemdaHandler godoc
//
// @Summary Sync Tujuan pemda
// @Description Sinkron data tujuan pemda berdasarkan tahun
// @Tags Pemda
// @Accept json
// @Produce json
//
// @Param payload body web.SyncPenetapanRequest true "Payload sync penetapan pemda"
//
// @Success 200 {object} web.Response[web.SyncPenetapanResponse] "Success"
// @Failure 400 {object} web.ValidationErrorResponse "Bad Request"
// @Failure 500 {object} web.ErrorResponse "Internal Server Error"
//
// @Router /pemda/tujuan/sync [post]
func (app *Application) SyncPenetapanTujuanPemdaHandler(
	w http.ResponseWriter,
	r *http.Request,
) {
	input := web.SyncPenetapanRequest{}
	errors := map[string]string{}

	err := app.ReadJSON(w, r, &input)
	if err != nil {
		errors["invalid_request"] = err.Error()
		app.BadRequestResponse(
			w, r,
			web.ValidationErrorResponse{
				Error: errors,
			},
		)
		return
	}

	request := &web.SyncPenetapanRequest{
		Tahun: input.Tahun,
	}

	v := validator.New()
	if web.ValidateSyncPenetapanRequest(v, request); !v.Valid() {
		app.FailedValidationResponse(w, r, v.Errors)
		return
	}

	result, err := app.PemdaService.SyncPenetapanTujuanPemda(
		r.Context(),
		request,
	)
	if err != nil {
		app.ServerErrorResponse(w, r, err)
		return
	}

	response := web.Response[web.SyncPenetapanResponse]{
		Data: result,
	}

	err = app.WriteJSON(w, http.StatusOK, response, nil)
	if err != nil {
		app.ServerErrorResponse(w, r, err)
		return
	}

}

// FindTujuanPemdaHandler godoc
//
// @Summary Get tujuan Pemda penetapan
// @Description Mengambil snapshot tujuan Pemda aktif berdasarkan tahun
// @Tags Pemda
// @Accept json
// @Produce json
// @Param tahun query int true "Tahun Penetapan"
// @Success 200 {object} web.Response[web.TujuanPenetapanPemdaResponse] "Success"
// @Failure 400 {object} web.ValidationErrorResponse "Bad Request"
// @Failure 500 {object} web.ErrorResponse "Internal Server Error"
// @Router /pemda/tujuan [get]
// GENERATED BY CODEX START: handler GET tujuan Pemda dari snapshot internal.
func (app *Application) FindTujuanPemdaHandler(
	w http.ResponseWriter,
	r *http.Request,
) {
	tahun, ok := app.parseTahunPemdaQuery(w, r)
	if !ok {
		return
	}

	result, err := app.PemdaService.FindTujuanPemda(r.Context(), tahun)
	if err != nil {
		app.ServerErrorResponse(w, r, err)
		return
	}

	if err := app.WriteJSON(w, http.StatusOK, web.Response[web.TujuanPenetapanPemdaResponse]{Data: result}, nil); err != nil {
		app.ServerErrorResponse(w, r, err)
	}
}

// FindSasaranPemdaHandler godoc
//
// @Summary Get sasaran Pemda penetapan
// @Description Mengambil snapshot sasaran Pemda aktif berdasarkan tahun
// @Tags Pemda
// @Accept json
// @Produce json
// @Param tahun query int true "Tahun Penetapan"
// @Success 200 {object} web.Response[web.SasaranPenetapanPemdaResponse] "Success"
// @Failure 400 {object} web.ValidationErrorResponse "Bad Request"
// @Failure 500 {object} web.ErrorResponse "Internal Server Error"
// @Router /pemda/sasaran [get]
func (app *Application) FindSasaranPemdaHandler(
	w http.ResponseWriter,
	r *http.Request,
) {
	tahun, ok := app.parseTahunPemdaQuery(w, r)
	if !ok {
		return
	}

	result, err := app.PemdaService.FindSasaranPemda(r.Context(), tahun)
	if err != nil {
		app.ServerErrorResponse(w, r, err)
		return
	}

	if err := app.WriteJSON(w, http.StatusOK, web.Response[web.SasaranPenetapanPemdaResponse]{Data: result}, nil); err != nil {
		app.ServerErrorResponse(w, r, err)
	}
}

func (app *Application) parseTahunPemdaQuery(w http.ResponseWriter, r *http.Request) (int, bool) {
	tahunStr := r.URL.Query().Get("tahun")
	if tahunStr == "" {
		app.BadRequestResponse(w, r, web.ValidationErrorResponse{
			Error: map[string]string{"tahun": "required"},
		})
		return 0, false
	}

	tahun, err := strconv.Atoi(tahunStr)
	if err != nil {
		app.BadRequestResponse(w, r, web.ValidationErrorResponse{
			Error: map[string]string{"tahun": "tahun tidak valid"},
		})
		return 0, false
	}

	return tahun, true
}

// GENERATED BY CODEX END

// SyncPenetapanSasaranPemdaHandler godoc
//
// @Summary Sync sasaran Pemda
// @Description Sinkron data sasaran Pemda berdasarkan tahun
// @Tags Pemda
// @Accept json
// @Produce json
// @Param payload body web.SyncPenetapanRequest true "Payload sync penetapan Pemda"
// @Success 200 {object} web.Response[web.SyncPenetapanResponse] "Success"
// @Failure 400 {object} web.ValidationErrorResponse "Bad Request"
// @Failure 500 {object} web.ErrorResponse "Internal Server Error"
// @Router /pemda/sasaran/sync [post]
// GENERATED BY CODEX START: handler sinkronisasi sasaran Pemda.
func (app *Application) SyncPenetapanSasaranPemdaHandler(
	w http.ResponseWriter,
	r *http.Request,
) {
	input := web.SyncPenetapanRequest{}
	if err := app.ReadJSON(w, r, &input); err != nil {
		app.BadRequestResponse(w, r, web.ValidationErrorResponse{
			Error: map[string]string{"invalid_request": err.Error()},
		})
		return
	}

	request := &web.SyncPenetapanRequest{Tahun: input.Tahun}
	v := validator.New()
	if web.ValidateSyncPenetapanRequest(v, request); !v.Valid() {
		app.FailedValidationResponse(w, r, v.Errors)
		return
	}

	result, err := app.PemdaService.SyncPenetapanSasaranPemda(r.Context(), request)
	if err != nil {
		app.ServerErrorResponse(w, r, err)
		return
	}

	if err := app.WriteJSON(w, http.StatusOK, web.Response[web.SyncPenetapanResponse]{Data: result}, nil); err != nil {
		app.ServerErrorResponse(w, r, err)
	}
}

// GENERATED BY CODEX END
