# RESTCLIENT HTTP TEST
# restclient-env: C-c C-e penetapan-http-env.json (khusus emacs)

# HEALTHCHECK
## OK
GET :baseUrl/healthcheck

## ERROR METHOD NOT ALLOWED
POST :baseUrl/healthcheck

## ERROR NOT FOUND
POST :baseUrl/healthcheck/123

# SWAGGER
GET :baseUrl/v3/api-docs


# OPD
## SYNC PENETAPAN OPD
POST :baseUrl/opd/sync_penetapan/tujuan
Content-Type: application/json

{
    "kode_opd": "5.01.5.05.0.00.01.0000",
    "tahun": 2026
}

## SYNC PENETAPAN OPD SASARAN
POST :baseUrl/opd/sync_penetapan/sasaran
Content-Type: application/json

{
    "kode_opd": "5.01.5.05.0.00.01.0000",
    "tahun": 2026
}

## BAD REQUEST SYNC TUJUAN OPD PENETAPAN
POST :baseUrl/opd/sync_penetapan
Content-Type: application/json

{
    "kode_opd": "2.55.66",
    "tahun": 2006
}


## TUJUAN OPD PENETAPAN
### OK
GET :baseUrl/opd/tujuan?kodeOpd=5.01.5.05.0.00.01.0000&tahun=2026

### BAD REQUEST
GET :baseUrl/opd/tujuan

### BAD REQUEST TAHUN REQUIRED
GET :baseUrl/opd/tujuan?kodeOpd=2.55.66

### BAD REQUEST TAHUN INVALID (not int)
GET :baseUrl/opd/tujuan?kodeOpd=2.55.66&tahun=2026_error

## SASARAN OPD PENETAPAN
GET :baseUrl/opd/sasaran?kodeOpd=5.01.5.05.0.00.01.0000&tahun=2026

### BAD REQUEST
GET :baseUrl/opd/sasaran

### BAD REQUEST TAHUN REQUIRED
GET :baseUrl/opd/sasaran?kodeOpd=2.55.66

### BAD REQUEST TAHUN INVALID (not int)
GET :baseUrl/opd/sasaran?kodeOpd=2.55.66&tahun=2026_error

## RENJA PENETAPAN
GET :baseUrl/opd/renja?kodeOpd=2.55.66&tahun=2026

## RENAKSI OPD
GET :baseUrl/opd/renaksi?kodeOpd=2.55&tahun=2026

# INVIDIU
## REKIN
GET :baseUrl/individu/rekin?pegawaiId=122333&levelPegawai=5&kodeOpd=2.55&tahun=2026

## RENAKSI
GET :baseUrl/individu/renaksi?pegawaiId=122333&levelPegawai=5&kodeOpd=2.55&tahun=2026&bulan=3
