-- GENERATED BY CODEX START: snapshot sasaran Pemda, indikator, dan target.
CREATE TABLE sasaran_pemda_penetapan (
    id BIGSERIAL PRIMARY KEY,
    penetapan_pemda_id BIGINT NOT NULL,
    kode_sasaran_pemda VARCHAR(255) NOT NULL,
    sasaran_pemda TEXT NOT NULL,
    periode VARCHAR(50) NOT NULL,
    tahun_aktif INTEGER NOT NULL,
    created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),

    CONSTRAINT fk_sasaran_pemda_penetapan
        FOREIGN KEY (penetapan_pemda_id)
        REFERENCES penetapan_pemda(id)
        ON DELETE CASCADE,
    CONSTRAINT uq_sasaran_pemda_penetapan
        UNIQUE (penetapan_pemda_id, kode_sasaran_pemda)
);

CREATE INDEX idx_sasaran_pemda_penetapan_parent
    ON sasaran_pemda_penetapan (penetapan_pemda_id);
CREATE INDEX idx_sasaran_pemda_penetapan_lookup
    ON sasaran_pemda_penetapan (tahun_aktif);

CREATE TABLE indikator_sasaran_pemda_penetapan (
    id BIGSERIAL PRIMARY KEY,
    sasaran_pemda_id BIGINT NOT NULL,
    kode_indikator VARCHAR(255) NOT NULL,
    indikator TEXT NOT NULL,
    rumus_perhitungan TEXT,
    sumber_data TEXT,
    definisi_operasional TEXT,
    tahun_aktif INTEGER NOT NULL,
    created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),

    CONSTRAINT fk_indikator_sasaran_pemda_penetapan
        FOREIGN KEY (sasaran_pemda_id)
        REFERENCES sasaran_pemda_penetapan(id)
        ON DELETE CASCADE,
    CONSTRAINT uq_indikator_sasaran_pemda_penetapan
        UNIQUE (sasaran_pemda_id, kode_indikator)
);

CREATE INDEX idx_indikator_sasaran_pemda_penetapan_parent
    ON indikator_sasaran_pemda_penetapan (sasaran_pemda_id);

CREATE TABLE target_indikator_sasaran_pemda_penetapan (
    id BIGSERIAL PRIMARY KEY,
    indikator_sasaran_pemda_id BIGINT NOT NULL,
    kode_target VARCHAR(255) NOT NULL,
    tahun INTEGER NOT NULL,
    target NUMERIC(20,4) NOT NULL,
    satuan VARCHAR(50) NOT NULL,
    created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),

    CONSTRAINT fk_target_indikator_sasaran_pemda_penetapan
        FOREIGN KEY (indikator_sasaran_pemda_id)
        REFERENCES indikator_sasaran_pemda_penetapan(id)
        ON DELETE CASCADE,
    CONSTRAINT uq_target_indikator_sasaran_pemda_penetapan
        UNIQUE (indikator_sasaran_pemda_id, kode_target)
);

CREATE INDEX idx_target_indikator_sasaran_pemda_penetapan_parent
    ON target_indikator_sasaran_pemda_penetapan (indikator_sasaran_pemda_id);
-- GENERATED BY CODEX END
