package main

import (
	"database/sql"
	"log/slog"
	"time"

	"github.com/bappeda-dev-team/penetapan-service/internal/api"
	"github.com/bappeda-dev-team/penetapan-service/internal/client/perencanaan"
	"github.com/bappeda-dev-team/penetapan-service/internal/repository"

	clientIndividu "github.com/bappeda-dev-team/penetapan-service/internal/individu/client"
	repoIndividu "github.com/bappeda-dev-team/penetapan-service/internal/individu/repository"
	serviceIndividu "github.com/bappeda-dev-team/penetapan-service/internal/individu/service"
	syncIndividu "github.com/bappeda-dev-team/penetapan-service/internal/individu/service/sync"

	clientPemda "github.com/bappeda-dev-team/penetapan-service/internal/pemda/client"
	repoPemda "github.com/bappeda-dev-team/penetapan-service/internal/pemda/repository"
	servicePemda "github.com/bappeda-dev-team/penetapan-service/internal/pemda/service"
	syncPemda "github.com/bappeda-dev-team/penetapan-service/internal/pemda/service/sync"

	serviceOpd "github.com/bappeda-dev-team/penetapan-service/internal/service/opd"
	syncOpd "github.com/bappeda-dev-team/penetapan-service/internal/service/opd/sync"

	"net/http"
)

// buildApplication adalah fungsi untuk injeksi repo dan service
// tambahkan service dan repository baru kesini
func buildApplication(
	cfg api.Config,
	logger *slog.Logger,
	db *sql.DB,
) *api.Application {

	// repository
	penetapanOpdRepo := repository.NewPenetapanOpdRepository(db)

	// external service
	perencanaanClient := perencanaan.NewPerencanaanClient(
		cfg.Services.Perencanaan.BaseURL,
		cfg.Services.Perencanaan.ApiPath,
		&http.Client{Timeout: 60 * time.Second},
	)

	// executor
	//// tujuan
	tujuanSyncExecutor := syncOpd.NewTujuanSyncExecutor(
		penetapanOpdRepo,
		perencanaanClient,
		logger,
	)

	//// sasaran
	sasaranSyncExecutor := syncOpd.NewSasaranSyncExecutor(
		penetapanOpdRepo,
		perencanaanClient,
		logger,
	)

	//// renja
	renjaSyncExecutor := syncOpd.NewRenjaSyncExecutor(
		penetapanOpdRepo,
		perencanaanClient,
		logger,
	)

	// register executor
	syncRegistry := &syncOpd.Registry{
		TujuanSyncExecutor:  tujuanSyncExecutor,
		SasaranSyncExecutor: sasaranSyncExecutor,
		RenjaSyncExecutor:   renjaSyncExecutor,
	}

	// service
	penetapanOpdService := serviceOpd.NewPenetapanOpdService(
		penetapanOpdRepo,
		perencanaanClient,
		syncRegistry,
		logger,
	)

	// individu
	// external service
	individuClient := clientIndividu.NewClient(
		cfg.Services.Individu.BaseURL,
		cfg.Services.Individu.ApiPath,
		&http.Client{Timeout: 60 * time.Second},
	)
	// repository
	penetapanIndiRepo := repoIndividu.NewPenetapanIndividuRepository(db)
	// executor
	//// tujuan
	pkSyncExecutor := syncIndividu.NewPkSyncExecutor(
		penetapanIndiRepo,
		individuClient,
		logger,
	)

	// exeuctor individu
	syncIndividuRegistry := &syncIndividu.Registry{
		PkSyncExecutor: pkSyncExecutor,
	}

	individuService := serviceIndividu.NewPenetapanIndividuService(
		penetapanIndiRepo,
		individuClient,
		syncIndividuRegistry,
		logger,
	)

	// pemda
	// repository
	penetapanPemdaRepo := repoPemda.NewPenetapanPemdaRepository(db)

	// external service
	pemdaClient := clientPemda.NewClient(
		cfg.Services.Pemda.BaseURL,
		cfg.Services.Pemda.ApiPath,
		&http.Client{Timeout: 60 * time.Second},
	)

	// executor
	//// tujuan pemda
	tujuanPemdaSyncExecutor := syncPemda.NewTujuanSyncExecutor(
		penetapanPemdaRepo,
		pemdaClient,
		logger,
	)
	// GENERATED BY CODEX START: executor sinkronisasi sasaran Pemda.
	sasaranPemdaSyncExecutor := syncPemda.NewSasaranSyncExecutor(
		penetapanPemdaRepo,
		pemdaClient,
		logger,
	)
	// GENERATED BY CODEX END

	// sync registry
	syncPemdaRegistry := &syncPemda.Registry{
		TujuanPemdaSyncExecutor:  tujuanPemdaSyncExecutor,
		SasaranPemdaSyncExecutor: sasaranPemdaSyncExecutor,
	}

	pemdaService := servicePemda.NewPenetapanPemdaService(
		penetapanPemdaRepo,
		pemdaClient,
		syncPemdaRegistry,
		logger,
	)

	// application
	app := &api.Application{
		Config: cfg,
		Logger: logger,

		PenetapanOpdService: penetapanOpdService,
		IndividuService:     individuService,
		PemdaService:        pemdaService,
	}

	return app
}
