package domain

import "time"

// GENERATED BY CODEX START: domain snapshot sasaran Pemda dan turunannya.
type SasaranPemdaPenetapan struct {
	Id               int64
	KodeSasaranPemda string
	SasaranPemda     string
	Periode          string
	TahunAktif       int
	CreatedDate      time.Time
	LastModifiedDate time.Time
	CreatedBy        *string
	PenetapanPemdaId int64
	Versi            int
	Indikator        []IndikatorSasaranPemdaPenetapan
}

type IndikatorSasaranPemdaPenetapan struct {
	Id                  int64
	IdSasaranPemda      int64
	KodeIndikator       string
	Indikator           string
	RumusPerhitungan    *string
	SumberData          *string
	DefinisiOperasional *string
	TahunAktif          int
	CreatedDate         time.Time
	LastModifiedDate    time.Time
	CreatedBy           *string
	Target              []TargetIndikatorSasaranPemdaPenetapan
}

type TargetIndikatorSasaranPemdaPenetapan struct {
	Id                 int64
	IndikatorSasaranId int64
	KodeTarget         string
	Tahun              int
	Target             float64
	Satuan             string
	CreatedDate        time.Time
	LastModifiedDate   time.Time
	CreatedBy          *string
}

// GENERATED BY CODEX END
