package sync

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"
	"slices"

	"github.com/bappeda-dev-team/penetapan-service/internal/common"
	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/client"
	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/domain"
	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/helper"
	helperPemda "github.com/bappeda-dev-team/penetapan-service/internal/pemda/helper"
	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/repository"
	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/web"
)

// GENERATED BY CODEX START: executor sinkronisasi sasaran Pemda.
type SasaranSyncExecutor struct {
	Repo   *repository.PenetapanPemdaRepository
	Client *client.Client
	Logger *slog.Logger
}

func NewSasaranSyncExecutor(
	repo *repository.PenetapanPemdaRepository,
	client *client.Client,
	logger *slog.Logger,
) *SasaranSyncExecutor {
	return &SasaranSyncExecutor{
		Repo:   repo,
		Client: client,
		Logger: logger,
	}
}

func (ex *SasaranSyncExecutor) Sync(
	ctx context.Context,
	syncID int64,
	req *web.SyncPenetapanRequest,
	currentUser string,
) (web.SyncPenetapanSummary, error) {
	request := client.SyncRequest{
		Tahun: req.Tahun,
	}
	// outsource
	sasarans, err := ex.Client.SyncSasaranPemdaPenetapan(ctx, request)
	if err != nil {
		return web.SyncPenetapanSummary{}, err
	}

	if !hasValidSasaranPemda(sasarans) {
		return web.SyncPenetapanSummary{}, common.NewValidation(
			"tidak ada data penetapan yang siap disinkronkan",
		)
	}

	tx, err := ex.Repo.DB.BeginTx(ctx, nil)
	if err != nil {
		ex.Logger.Error("inisialisasi transaksi sync sasaran Pemda gagal", "err", err)
		return web.SyncPenetapanSummary{}, err
	}
	defer func() {
		_ = tx.Rollback()
	}()

	snapshotID, err := ex.createActiveSnapshot(
		ctx,
		tx,
		domain.SnapshotPenetapan{
			JenisSnapshot: domain.JenisPenetapanSasaranPemda,
			Tahun:         req.Tahun,
		},
		currentUser,
	)
	if err != nil {
		return web.SyncPenetapanSummary{}, err
	}

	summary := SummaryCounter{}
	for _, sasaran := range sasarans {
		kodeTujuan := fmt.Sprintf("TUJ-PEMDA-%d", sasaran.TujuanPemdaId)
		kodeSasaran := fmt.Sprintf("SAS-PEMDA-%d", sasaran.Id)
		periodeSasaran := fmt.Sprintf("%s-%s",
			sasaran.Periode.TahunAwal,
			sasaran.Periode.TahunAkhir)
		tahunAktif := req.Tahun
		sasaranClean := helperPemda.TextCleaner(sasaran.SasaranPemda)
		sasaranPemda := domain.SasaranPemdaPenetapan{
			KodeTujuanPemda:  kodeTujuan,
			KodeSasaranPemda: kodeSasaran,
			SasaranPemda:     sasaranClean,
			Periode:          periodeSasaran,
			TahunAktif:       tahunAktif,
			CreatedBy:        &currentUser,
			PenetapanPemdaId: snapshotID,
		}
		sasaranID, err := ex.Repo.SaveSasaranPemdaPenetapan(ctx, tx, sasaranPemda)
		if err != nil {
			return web.SyncPenetapanSummary{}, err
		}
		summary.AddSasaranPemda(1)

		for _, indikator := range sasaran.Indikator {
			indikatorClean := helperPemda.TextCleaner(indikator.Indikator)
			indikatorID, err := ex.Repo.SaveIndikatorSasaranPemdaPenetapan(
				ctx,
				tx,
				domain.IndikatorSasaranPemdaPenetapan{
					IdSasaranPemda:      sasaranID,
					KodeIndikator:       fmt.Sprintf("IND-%d", indikator.Id),
					Indikator:           indikatorClean,
					RumusPerhitungan:    &indikator.RumusPerhitungan,
					SumberData:          &indikator.SumberData,
					DefinisiOperasional: &indikator.DefinisiOperasional,
					TahunAktif:          req.Tahun,
					CreatedBy:           &currentUser,
				},
			)
			if err != nil {
				return web.SyncPenetapanSummary{}, err
			}
			summary.AddIndikator(1)

			for _, target := range indikator.TargetPenetapan {
				tahun, errTahun := helper.ParseTahun(target.Tahun)
				if errTahun != nil {
					return web.SyncPenetapanSummary{}, errTahun
				}

				if _, err := ex.Repo.SaveTargetIndikatorSasaranPemdaPenetapan(
					ctx,
					tx,
					domain.TargetIndikatorSasaranPemdaPenetapan{
						IndikatorSasaranId: indikatorID,
						KodeTarget:         fmt.Sprintf("TGT-%d", target.Id),
						Tahun:              tahun,
						Target:             target.Target,
						Satuan:             target.Satuan,
						CreatedBy:          &currentUser,
					},
				); err != nil {
					return web.SyncPenetapanSummary{}, err
				}
				summary.AddTarget(1)
			}
		}
	}

	if err := tx.Commit(); err != nil {
		return web.SyncPenetapanSummary{}, err
	}

	return summary.Response(), nil
}

func (ex *SasaranSyncExecutor) createActiveSnapshot(
	ctx context.Context,
	tx *sql.Tx,
	snapshot domain.SnapshotPenetapan,
	currentUser string,
) (int64, error) {
	versi, err := ex.Repo.GetPenetapanNextVersion(ctx, tx, snapshot)
	if err != nil {
		return 0, err
	}

	if versi > 1 {
		if err := ex.Repo.DeactivateOldSnapshot(ctx, tx, snapshot); err != nil {
			return 0, err
		}
	}

	snapshot.Versi = versi
	snapshot.SnapshotStatus = domain.SnapshotStatusActive
	snapshot.GeneratedBy = &currentUser
	snapshot.IsActive = true

	snapshotID, err := ex.Repo.SaveSnapshot(ctx, tx, snapshot)
	if err != nil {
		ex.Logger.Error("simpan snapshot sasaran Pemda gagal", "snapshot", snapshot)
		return 0, err
	}

	return snapshotID, nil
}

// GENERATED BY CODEX END

func hasValidSasaranPemda(sasaranPemdas []client.SasaranPemdaPenetapanResponse) bool {
	for _, sasaran := range sasaranPemdas {
		if !helperPemda.IsValidSasaran(sasaran) {
			continue
		}

		for _, indikator := range sasaran.Indikator {
			if !helperPemda.IsValidIndikator(indikator) {
				continue
			}

			if slices.ContainsFunc(indikator.TargetPenetapan, helperPemda.IsValidTarget) {
				return true
			}
		}
	}

	return false
}
