package sync

import "github.com/bappeda-dev-team/penetapan-service/internal/pemda/web"

type SummaryCounter struct {
	TujuanPemda  int
	SasaranPemda int
	Indikator    int
	Target       int
}

func (s *SummaryCounter) AddTujuanPemda(n int) {
	s.TujuanPemda += n
}

// GENERATED BY CODEX START: counter ringkasan sasaran Pemda.
func (s *SummaryCounter) AddSasaranPemda(n int) {
	s.SasaranPemda += n
}

// GENERATED BY CODEX END

func (s *SummaryCounter) AddIndikator(n int) {
	s.Indikator += n
}

func (s *SummaryCounter) AddTarget(n int) {
	s.Target += n
}

func (s SummaryCounter) Response() web.SyncPenetapanSummary {
	var tujuanPemda *int
	var sasaranPemda *int
	if s.TujuanPemda > 0 {
		tujuanPemda = &s.TujuanPemda
	}
	if s.SasaranPemda > 0 {
		sasaranPemda = &s.SasaranPemda
	}
	return web.SyncPenetapanSummary{
		TujuanPemda:  tujuanPemda,
		SasaranPemda: sasaranPemda,
		Indikator:    s.Indikator,
		Target:       s.Target,
	}
}
