package sync

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"
	"slices"
	"strconv"

	"github.com/bappeda-dev-team/penetapan-service/internal/common"
	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/client"
	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/domain"
	helperPemda "github.com/bappeda-dev-team/penetapan-service/internal/pemda/helper"
	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/repository"
	"github.com/bappeda-dev-team/penetapan-service/internal/pemda/web"
)

type TujuanSyncExecutor struct {
	Repo   *repository.PenetapanPemdaRepository
	Client *client.Client
	Logger *slog.Logger
}

func NewTujuanSyncExecutor(
	repo *repository.PenetapanPemdaRepository,
	client *client.Client,
	logger *slog.Logger,
) *TujuanSyncExecutor {
	return &TujuanSyncExecutor{
		Repo:   repo,
		Client: client,
		Logger: logger,
	}
}

func (ex *TujuanSyncExecutor) Sync(
	ctx context.Context,
	syncId int64,
	req *web.SyncPenetapanRequest,
	currentUser string,
) (web.SyncPenetapanSummary, error) {
	request := client.SyncRequest{
		Tahun: req.Tahun,
	}
	// outsource
	tujuanPemdas, err := ex.Client.SyncTujuanPemdaPenetapan(ctx, request)
	if err != nil {
		return web.SyncPenetapanSummary{}, err
	}

	if !hasValidTujuanPemda(tujuanPemdas) {
		return web.SyncPenetapanSummary{}, common.NewValidation(
			"tidak ada data penetapan yang siap disinkronkan",
		)
	}
	// db
	tx, err := ex.Repo.DB.BeginTx(ctx, nil)
	if err != nil {
		ex.Logger.Error("ERROR Initializing DB", "err", err)
		return web.SyncPenetapanSummary{}, err
	}
	defer func() {
		_ = tx.Rollback()
	}()

	snapshot := domain.SnapshotPenetapan{
		JenisSnapshot: domain.JenisPenetapanTujuanPemda,
		Tahun:         req.Tahun,
	}

	snapshotId, err := ex.createActiveSnapshot(ctx, tx, snapshot, currentUser)
	if err != nil {
		return web.SyncPenetapanSummary{}, err
	}

	// GENERATED BY CODEX START: persist tujuan Pemda, indikator, dan target penetapan.
	summary := SummaryCounter{}
	for _, tujuan := range tujuanPemdas {
		kodeTujuan := fmt.Sprintf("TUJ-PEMDA-%d", tujuan.Id)
		periodeTujuan := fmt.Sprintf("%s-%s",
			tujuan.Periode.TahunAwal,
			tujuan.Periode.TahunAkhir)
		tahunAktif := req.Tahun
		visiPemda := helperPemda.TextCleaner(tujuan.Visi)
		misiPemda := helperPemda.TextCleaner(tujuan.Misi)
		tujuanClean := helperPemda.TextCleaner(tujuan.TujuanPemda)
		tujuanPemda := domain.TujuanPemdaPenetapan{
			KodeTujuanPemda:  kodeTujuan,
			Visi:             visiPemda,
			Misi:             misiPemda,
			TujuanPemda:      tujuanClean,
			Periode:          periodeTujuan,
			TahunAktif:       tahunAktif,
			CreatedBy:        &currentUser,
			PenetapanPemdaId: snapshotId,
		}
		tujuanID, err := ex.Repo.SaveTujuanPemdaPenetapan(ctx, tx, tujuanPemda)
		if err != nil {
			return web.SyncPenetapanSummary{}, err
		}
		summary.AddTujuanPemda(1)

		for _, indikator := range tujuan.Indikator {
			indikatorClean := helperPemda.TextCleaner(indikator.Indikator)
			indikatorTujuan := domain.IndikatorTujuanPemdaPenetapan{
				IdTujuanPemda:       tujuanID,
				KodeIndikator:       fmt.Sprintf("IND-%d", indikator.Id),
				Indikator:           indikatorClean,
				RumusPerhitungan:    &indikator.RumusPerhitungan,
				SumberData:          &indikator.SumberData,
				DefinisiOperasional: &indikator.DefinisiOperasional,
				TahunAktif:          req.Tahun,
				CreatedBy:           &currentUser,
			}
			indikatorID, err := ex.Repo.SaveIndikatorTujuanPemdaPenetapan(
				ctx, tx, indikatorTujuan)
			if err != nil {
				return web.SyncPenetapanSummary{}, err
			}
			summary.AddIndikator(1)

			for _, target := range indikator.TargetPenetapan {
				tahunTarget, err := strconv.Atoi(target.Tahun)
				if err != nil {
					return web.SyncPenetapanSummary{}, fmt.Errorf(
						"tahun target indikator %q tidak valid: %w", indikator.Indikator, err)
				}

				targetTujuan := domain.TargetIndikatorTujuanPemdaPenetapan{
					IndikatorTujuanPemdaId: indikatorID,
					KodeTarget:             fmt.Sprintf("TGT-%d", target.Id),
					Tahun:                  tahunTarget,
					Target:                 target.Target,
					Satuan:                 target.Satuan,
					CreatedBy:              &currentUser,
				}
				if _, err := ex.Repo.SaveTargetIndikatorTujuanPemdaPenetapan(
					ctx, tx, targetTujuan); err != nil {
					return web.SyncPenetapanSummary{}, err
				}
				summary.AddTarget(1)
			}
		}
	}
	// GENERATED BY CODEX END

	// GENERATED BY CODEX START: finalisasi transaksi sinkronisasi.
	if err := tx.Commit(); err != nil {
		return web.SyncPenetapanSummary{}, err
	}

	response := summary.Response()
	// GENERATED BY CODEX END
	return response, nil
}

func (ex *TujuanSyncExecutor) createActiveSnapshot(
	ctx context.Context,
	tx *sql.Tx,
	snapshot domain.SnapshotPenetapan,
	currentUser string,
) (int64, error) {
	versi, err := ex.Repo.GetPenetapanNextVersion(ctx, tx, snapshot)
	if err != nil {
		return 0, err
	}

	if versi > 1 {
		if err := ex.Repo.DeactivateOldSnapshot(ctx, tx, snapshot); err != nil {
			return 0, err
		}
	}

	snapshot.Versi = versi
	snapshot.SnapshotStatus = domain.SnapshotStatusActive
	snapshot.GeneratedBy = &currentUser
	snapshot.IsActive = true

	snapshotID, err := ex.Repo.SaveSnapshot(ctx, tx, snapshot)
	if err != nil {
		ex.Logger.Error("save penetapan individu error", "snapshot", snapshot)
		return 0, err
	}

	return snapshotID, nil
}

func hasValidTujuanPemda(tujuanPemdas []client.TujuanPemdaPenetapanResponse) bool {
	for _, tujuan := range tujuanPemdas {
		if !helperPemda.IsValidTujuan(tujuan) {
			continue
		}

		for _, indikator := range tujuan.Indikator {
			if !helperPemda.IsValidIndikator(indikator) {
				continue
			}

			if slices.ContainsFunc(indikator.TargetPenetapan, helperPemda.IsValidTarget) {
				return true
			}
		}
	}

	return false
}
