// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Kertaskerja Dev Team"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthcheck": {
            "get": {
                "description": "checking if this service is accessible",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "healthcheck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.Response-web_HealthcheckResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/opd/sasaran": {
            "get": {
                "description": "Mengambil data sasaran OPD berdasarkan kode OPD dan tahun penetapan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OPD"
                ],
                "summary": "Get sasaran OPD penetapan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kode OPD",
                        "name": "kodeOpd",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tahun Penetapan",
                        "name": "tahun",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data sasaran OPD",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/web.Response-web_SasaranPenetapanOpdResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/opd/sasaran/sync": {
            "post": {
                "description": "Sinkron data penetapan sasaran OPD berdasarkan kode OPD dan tahun dari perencanaan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sync"
                ],
                "summary": "Sync Penetapan Sasaran OPD",
                "parameters": [
                    {
                        "description": "Payload sinkronisasi penetapan OPD",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.SyncPenetapanOpdRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/web.Response-web_SyncPenetapanOpdResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/opd/tujuan": {
            "get": {
                "description": "Mengambil data tujuan OPD berdasarkan kode OPD dan tahun penetapan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OPD"
                ],
                "summary": "Get tujuan OPD penetapan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kode OPD",
                        "name": "kodeOpd",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tahun Penetapan",
                        "name": "tahun",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data tujuan OPD",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/web.Response-web_TujuanPenetapanOpdResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/opd/tujuan/sync": {
            "post": {
                "description": "Sinkron data penetapan tujuan OPD berdasarkan kode OPD dan tahun dari perencanaan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sync"
                ],
                "summary": "Sync Penetapan Tujuan OPD",
                "parameters": [
                    {
                        "description": "Payload sinkronisasi penetapan OPD",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.SyncPenetapanOpdRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/web.Response-web_SyncPenetapanOpdResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "web.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {}
            }
        },
        "web.HealthcheckResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "system_info": {
                    "$ref": "#/definitions/web.HealthcheckSystemInfo"
                }
            }
        },
        "web.HealthcheckSystemInfo": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "web.IndikatorSasaranPenetapanResponse": {
            "type": "object",
            "properties": {
                "definisi_operasional": {
                    "type": "string",
                    "example": "definisi abc"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "id_sasaran_opd": {
                    "type": "integer",
                    "example": 11
                },
                "indikator": {
                    "type": "string",
                    "example": "Indikator kepuasa publik"
                },
                "rumus_perhitungan": {
                    "type": "string",
                    "example": "indeks kepuasan masyarakat"
                },
                "sumber_data": {
                    "type": "string",
                    "example": "bps"
                },
                "tahun_aktif": {
                    "type": "integer",
                    "example": 2025
                },
                "target": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TargetIndikatorResponse"
                    }
                }
            }
        },
        "web.IndikatorTujuanPenetapanResponse": {
            "type": "object",
            "properties": {
                "definisi_operasional": {
                    "type": "string",
                    "example": "definisi abc"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "id_tujuan_opd": {
                    "type": "integer",
                    "example": 12
                },
                "indikator": {
                    "type": "string",
                    "example": "Indikator kepuasa publik"
                },
                "rumus_perhitungan": {
                    "type": "string",
                    "example": "indeks kepuasan masyarakat"
                },
                "sumber_data": {
                    "type": "string",
                    "example": "bps"
                },
                "tahun_aktif": {
                    "type": "integer",
                    "example": 2025
                },
                "target": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TargetIndikatorResponse"
                    }
                }
            }
        },
        "web.Response-web_HealthcheckResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.HealthcheckResponse"
                }
            }
        },
        "web.Response-web_SasaranPenetapanOpdResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.SasaranPenetapanOpdResponse"
                }
            }
        },
        "web.Response-web_SyncPenetapanOpdResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.SyncPenetapanOpdResponse"
                }
            }
        },
        "web.Response-web_TujuanPenetapanOpdResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.TujuanPenetapanOpdResponse"
                }
            }
        },
        "web.SasaranPenetapanOpdResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "indikator": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.IndikatorSasaranPenetapanResponse"
                    }
                },
                "kode_opd": {
                    "type": "string",
                    "example": "1.02.0.00.0.00.01.0000"
                },
                "kode_sasaran_opd": {
                    "type": "string",
                    "example": "SAS-001"
                },
                "periode": {
                    "type": "string",
                    "example": "2025-2029"
                },
                "sasaran_opd": {
                    "type": "string",
                    "example": "Meningkatnya Nilai SAKIP"
                },
                "tahun_aktif": {
                    "type": "integer",
                    "example": 2025
                },
                "versi": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "web.SyncPenetapanOpdRequest": {
            "type": "object",
            "properties": {
                "kode_opd": {
                    "type": "string",
                    "example": "1.22.33"
                },
                "tahun": {
                    "type": "integer",
                    "example": 2025
                }
            }
        },
        "web.SyncPenetapanOpdResponse": {
            "type": "object",
            "properties": {
                "jenis_penetapan": {
                    "type": "string",
                    "example": "TUJUAN-OPD"
                },
                "kode_opd": {
                    "type": "string",
                    "example": "1.22.33"
                },
                "processed_at": {
                    "type": "string"
                },
                "processed_summary": {
                    "$ref": "#/definitions/web.SyncPenetapanOpdSummary"
                },
                "status": {
                    "type": "string",
                    "example": "SUCCESS"
                },
                "sync_id": {
                    "type": "integer",
                    "example": 155
                },
                "tahun": {
                    "type": "integer",
                    "example": 2025
                }
            }
        },
        "web.SyncPenetapanOpdSummary": {
            "type": "object",
            "properties": {
                "indikator": {
                    "type": "integer",
                    "example": 3
                },
                "renja": {
                    "type": "integer",
                    "example": 1
                },
                "sasaran": {
                    "type": "integer",
                    "example": 1
                },
                "target": {
                    "type": "integer",
                    "example": 4
                },
                "tujuan": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "web.TargetIndikatorResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "indikator_id": {
                    "type": "integer",
                    "example": 44
                },
                "satuan": {
                    "type": "string",
                    "example": "%"
                },
                "tahun": {
                    "type": "integer",
                    "example": 2025
                },
                "target": {
                    "type": "number",
                    "example": 100
                }
            }
        },
        "web.TujuanPenetapanOpdResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "indikator": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.IndikatorTujuanPenetapanResponse"
                    }
                },
                "kode_opd": {
                    "type": "string",
                    "example": "1.02.0.00.0.00.01.0000"
                },
                "kode_tujuan_opd": {
                    "type": "string",
                    "example": "TUJ-001"
                },
                "periode": {
                    "type": "string",
                    "example": "2025-2029"
                },
                "tahun_aktif": {
                    "type": "integer",
                    "example": 2025
                },
                "tujuan_opd": {
                    "type": "string",
                    "example": "Meningkatkan kualitas pelayanan publik"
                },
                "versi": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "web.ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "kode_opd": "required",
                        "tahun": "required"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Penetapan Service",
	Description:      "Service snapshot penetapan tujuan, sasaran, renja, rekin untuk pemda, opd, dan individu",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
