info:
  contact: {}
paths:
  /v1/healthcheck:
    get:
      consumes:
      - application/json
      description: checking is this service is accessible
      produces:
      - application/json
      responses:
        "200":
          description: Service is healthy
          schema:
            additionalProperties: true
            type: object
      summary: healthcheck
      tags:
      - healthcheck
swagger: "2.0"
