package client

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"

	"github.com/bappeda-dev-team/penetapan-service/internal/client"
)

type Client struct {
	*client.BaseClient
}

func NewClient(host, apiPath string, httpClient *http.Client) *Client {
	return &Client{
		BaseClient: client.NewBaseClient(host, apiPath, httpClient),
	}
}

func (c *Client) SyncTujuanPemdaPenetapan(
	ctx context.Context,
	request SyncRequest,
) ([]TujuanPemdaPenetapanResponse, error) {
	// url
	baseUrl := fmt.Sprintf(
		"%s/tujuan_pemda/penetapan/%d",
		c.BaseURL,
		request.Tahun)

	// request
	req, err := http.NewRequest(http.MethodGet, baseUrl, nil)
	if err != nil {
		return nil, fmt.Errorf("Gagal membuat request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	// set session id
	sessionID := client.GetSessionID(ctx)
	if sessionID != "" {
		req.Header.Set("X-Session-Id", sessionID)
	} else {
		log.Printf("Tidak ada X-Session-Id ditemukan, mungkin akan 401")
	}

	// send request
	res, err := c.HttpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Request gagal: %w", err)
	}
	defer res.Body.Close()

	// response status
	if res.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("Request ke pk penetapan gagal. status: %d", res.StatusCode)
	}

	type wrapper struct {
		Code   int                            `json:"code"`
		Status string                         `json:"status"`
		Data   []TujuanPemdaPenetapanResponse `json:"data"`
	}

	var result wrapper
	if err := json.NewDecoder(res.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("gagal decode response: %w", err)
	}

	return result.Data, nil
}

// GENERATED BY CODEX START: request upstream sinkronisasi sasaran Pemda.
func (c *Client) SyncSasaranPemdaPenetapan(
	ctx context.Context,
	request SyncRequest,
) ([]SasaranPemdaPenetapanResponse, error) {
	baseURL := fmt.Sprintf("%s/sasaran_pemda/penetapan/%d", c.BaseURL, request.Tahun)

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, baseURL, nil)
	if err != nil {
		return nil, fmt.Errorf("gagal membuat request sinkronisasi sasaran Pemda: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	if sessionID := client.GetSessionID(ctx); sessionID != "" {
		req.Header.Set("X-Session-Id", sessionID)
	} else {
		log.Printf("Tidak ada X-Session-Id ditemukan, mungkin akan 401")
	}

	res, err := c.HttpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("request sinkronisasi sasaran Pemda gagal: %w", err)
	}
	defer res.Body.Close()

	if res.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("request sasaran Pemda gagal. status: %d", res.StatusCode)
	}

	type wrapper struct {
		Code   int                             `json:"code"`
		Status string                          `json:"status"`
		Data   []SasaranPemdaPenetapanResponse `json:"data"`
	}

	var result wrapper
	if err := json.NewDecoder(res.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("gagal decode response sasaran Pemda: %w", err)
	}

	return result.Data, nil
}

// GENERATED BY CODEX END
