package client

type TujuanPemdaPenetapanResponse struct {
	Id          int                              `json:"id"`
	IdVisi      int                              `json:"id_visi,omitempty"`
	Visi        string                           `json:"visi,omitempty"`
	IdMisi      int                              `json:"id_misi,omitempty"`
	Misi        string                           `json:"misi,omitempty"`
	TujuanPemda string                           `json:"tujuan_pemda"`
	TematikId   int                              `json:"tematik_id,omitempty"`
	NamaTematik string                           `json:"nama_tematik,omitempty"`
	IsLock      bool                             `json:"is_lock"`
	Periode     PeriodeResponse                  `json:"periode"`
	Indikator   []IndikatorPenetapanDualResponse `json:"indikator"`
}

type PeriodeResponse struct {
	TahunAwal    string `json:"tahun_awal"`
	TahunAkhir   string `json:"tahun_akhir"`
	JenisPeriode string `json:"jenis_periode"`
}

type IndikatorPenetapanDualResponse struct {
	Id                  int                  `json:"id"`
	KodeIndikator       string               `json:"kode_indikator"`
	Indikator           string               `json:"indikator"`
	RumusPerhitungan    string               `json:"rumus_perhitungan"`
	SumberData          string               `json:"sumber_data"`
	DefinisiOperasional string               `json:"definisi_operasional"`
	Jenis               string               `json:"jenis"`
	TargetRankhir       []TargetDualResponse `json:"target_rankhir"`
	TargetPenetapan     []TargetDualResponse `json:"target_penetapan"`
}

type TargetDualResponse struct {
	Id     int     `json:"id"`
	Target float64 `json:"target"`
	Satuan string  `json:"satuan"`
	Tahun  string  `json:"tahun"`
}

// GENERATED BY CODEX START: response upstream untuk sinkronisasi sasaran Pemda.
type SasaranPemdaPenetapanResponse struct {
	Id            int                              `json:"id"`
	IdTujuanPemda int                              `json:"id_tujuan_pemda,omitempty"`
	TujuanPemda   string                           `json:"tujuan_pemda,omitempty"`
	SasaranPemda  string                           `json:"sasaran_pemda"`
	Periode       PeriodeResponse                  `json:"periode"`
	Indikator     []IndikatorPenetapanDualResponse `json:"indikator"`
}

// GENERATED BY CODEX END
